# ユーザープロンプト

Your answer returns the following warning message:

```
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retrieved_refs_gpt_4['extracted_source'] = retrieved_refs_gpt_4['source'].apply(extract_formatted_strings)
```

Modify your previous answer to remove this warning. Don't include the definition of `extract_formatted_strings` since I copied that.


# LLMの出力結果

```python
# データフレームの特定の条件に一致する行を選択し、新しい列に関数の結果を格納する
retrieved_refs_gpt_4 = retrieved_refs.query(
    "(クエリID.str.startswith('2') or クエリID.str.startswith('3')) and モデル == 'gpt-4-0613'"
).copy()

retrieved_refs_gpt_4.loc[:, 'extracted_info'] = retrieved_refs_gpt_4['source'].apply(extract_formatted_strings)

# 結果を表示する
print(retrieved_refs_gpt_4)
```